version: '3.9'

services:
  postgres_dev:
    image: postgres:16
    container_name: pg_dev
    ports:
      - '5556:5432'
    environment:
      POSTGRES_DB: dev_database
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_password
    volumes:
      - ./data/dev:/var/lib/postgresql/data

  postgres_test:
    image: postgres:16
    container_name: pg_test
    ports:
      - '5557:5432'
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
    volumes:
      - ./data/test:/var/lib/postgresql/data
volumes:
  pgdata:
